Config = {
		Weapons = {
				[`WEAPON_ADVANCEDRIFLE`] = { object = `w_ar_advancedrifle`, item = 'WEAPON_ADVANCEDRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_ASSAULTRIFLE`] = { object = `w_ar_assaultrifle`, item = 'WEAPON_ASSAULTRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_ASSAULTRIFLE_MK2`] = { object = `w_ar_assaultriflemk2`, item = 'WEAPON_ASSAULTRIFLE_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_ASSAULTSHOTGUN`] = { object = `w_sg_assaultshotgun`, item = 'WEAPON_ASSAULTSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_ASSAULTSMG`] = { object = `w_sb_assaultsmg`, item = 'WEAPON_ASSAULTSMG', rotation = vector3(0,0,0)},
				[`WEAPON_BULLPUPRIFLE`] = { object = `w_ar_bullpuprifle`, item = 'WEAPON_BULLPUPRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_BULLPUPRIFLE_MK2`] = { object = `w_ar_bullpupriflemk2`, item = 'WEAPON_BULLPUPRIFLE_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_BULLPUPSHOTGUN`] = { object = `w_sg_bullpupshotgun`, item = 'WEAPON_BULLPUPSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_CARBINERIFLE`] = { object = `w_ar_carbinerifle`, item = 'WEAPON_CARBINERIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_CARBINERIFLE_MK2`] = { object = `w_ar_carbineriflemk2`, item = 'WEAPON_CARBINERIFLE_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_COMBATMG`] = { object = `w_mg_combatmg`, item = 'WEAPON_COMBATMG', rotation = vector3(0,0,0)},
				[`WEAPON_COMBATMG_MK2`] = { object = `w_mg_combatmgmk2`, item = 'WEAPON_COMBATMG_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_COMBATPDW`] = { object = `w_sb_pdw`, item = 'WEAPON_COMBATPDW', rotation = vector3(0,0,0)},
				[`WEAPON_COMBATSHOTGUN`] = { object = `w_sg_pumpshotgunh4`, item = 'WEAPON_COMBATSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_COMPACTRIFLE`] = { object = `w_ar_assaultrifle_smg`, item = 'WEAPON_COMPACTRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_DBSHOTGUN`] = { object = `w_sg_doublebarrel`, item = 'WEAPON_DBSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_FIREWORK`] = { object = `w_lr_firework`, item = 'WEAPON_FIREWORK', rotation = vector3(0,0,0)},
				[`WEAPON_GUSENBERG`] = { object = `w_sb_gusenberg`, item = 'WEAPON_GUSENBERG', rotation = vector3(0,0,0)},
				[`WEAPON_HEAVYRIFLE`] = { object = `w_ar_heavyrifleh`, item = 'WEAPON_HEAVYRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_HEAVYSHOTGUN`] = { object = `w_sg_heavyshotgun`, item = 'WEAPON_HEAVYSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_HEAVYSNIPER`] = { object = `w_sr_heavysniper`, item = 'WEAPON_HEAVYSNIPER', rotation = vector3(0,0,0)},
				[`WEAPON_HEAVYSNIPER_MK2`] = { object = `w_sr_heavysnipermk2`, item = 'WEAPON_HEAVYSNIPER_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_MARKSMANRIFLE`] = { object = `w_sr_marksmanrifle`, item = 'WEAPON_MARKSMANRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_MARKSMANRIFLE_MK2`] = { object = `w_sr_marksmanriflemk2`, item = 'WEAPON_MARKSMANRIFLE_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_MG`] = { object = `w_mg_mg`, item = 'WEAPON_MG', rotation = vector3(0,0,0)},
				[`WEAPON_MICROSMG`] = { object = `w_sb_microsmg`, item = 'WEAPON_MICROSMG', rotation = vector3(0,0,0)},
				[`WEAPON_MILITARYRIFLE`] = { object = `w_ar_bullpuprifleh4`, item = 'WEAPON_MILITARYRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_MINISMG`] = { object = `w_sb_minismg`, item = 'WEAPON_MINISMG', rotation = vector3(0,0,0)},
				[`WEAPON_MUSKET`] = { object = `w_ar_musket`, item = 'WEAPON_MUSKET', rotation = vector3(0,0,0)},
				[`WEAPON_PUMPSHOTGUN`] = { object = `w_sg_pumpshotgun`, item = 'WEAPON_PUMPSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_PUMPSHOTGUN_MK2`] = { object = `w_sg_pumpshotgunmk2`, item = 'WEAPON_PUMPSHOTGUN_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_SAWNOFFSHOTGUN`] = { object = `w_sg_sawnoff`, item = 'WEAPON_SAWNOFFSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_SMG`] = { object = `w_sb_smg`, item = 'WEAPON_SMG', rotation = vector3(0,0,0)},
				[`WEAPON_SMG_MK2`] = { object = `w_sb_smgmk2`, item = 'WEAPON_SMG_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_SNIPERRIFLE`] = { object = `w_sr_sniperrifle`, item = 'WEAPON_SNIPERRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_SPECIALCARBINE`] = { object = `w_ar_specialcarbine`, item = 'WEAPON_SPECIALCARBINE', rotation = vector3(0,0,0)},
				[`WEAPON_SPECIALCARBINE_MK2`] = { object = `w_ar_specialcarbinemk2`, item = 'WEAPON_SPECIALCARBINE_MK2', rotation = vector3(0,0,0)},
				[`WEAPON_AUTOSHOTGUN`] = { object = `w_sg_sweeper`, item = 'WEAPON_AUTOSHOTGUN', rotation = vector3(0,0,0)},
				[`WEAPON_PRECISIONRIFLE`] = { object = `w_sr_precisionrifle_reh`, item = 'WEAPON_PRECISIONRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_TACTICALRIFLE`] = { object = `w_ar_carbinerifle_reh`, item = 'WEAPON_TACTICALRIFLE', rotation = vector3(0,0,0)},
				[`WEAPON_RAYMINIGUN`] = { object = `w_mg_sminigun`, item = 'WEAPON_RAYMINIGUN', rotation = vector3(0,0,0)},
				[`WEAPON_RAYCARBINE`] = { object = `w_ar_srifle`, item = 'WEAPON_RAYCARBINE', rotation = vector3(0,0,0)},
				[`WEAPON_RAILGUN`] = { object = `w_ar_railgun`, item = 'WEAPON_RAILGUN', rotation = vector3(0,0,0)},
				[`WEAPON_RPG`] = { object = `w_lr_rpg`, item = 'WEAPON_RPG', rotation = vector3(0,0,0)},
				[`WEAPON_HOMINGLAUNCHER`] = { object = `w_lr_homing`, item = 'WEAPON_HOMINGLAUNCHER', rotation = vector3(0,0,0)},
				[`WEAPON_MINIGUN`] = { object = `w_mg_minigun`, item = 'WEAPON_MINIGUN', rotation = vector3(0,0,0)},
				-- MELEE
				[`WEAPON_BAT`] = {object = `w_me_bat`, item = 'WEAPON_BAT', rotation = vector3(0,92.5,0)},
				[`WEAPON_BATTLEAXE`] = {object = `w_me_battleaxe`, item = 'WEAPON_BATTLEAXE', rotation = vector3(0,92.5,0)},
				[`WEAPON_CROWBAR`] = {object = `w_me_crowbar`, item = 'WEAPON_CROWBAR', rotation = vector3(0,92.5,0)},
				[`WEAPON_FIREEXTINGUISHER`] = {object = `w_am_fire_exting`, item = 'WEAPON_FIREEXTINGUISHER', rotation = vector3(0,92.5,0)},
				[`WEAPON_GOLFCLUB`] = {object = `w_me_gclub`, item = 'WEAPON_GOLFCLUB', rotation = vector3(0,92.5,0)},
				[`WEAPON_HATCHET`] = {object = `w_me_hatchet`, item = 'WEAPON_HATCHET', rotation = vector3(0,92.5,0)},
				[`WEAPON_HAZARDCAN`] = {object = `w_ch_jerrycan`, item = 'WEAPON_HAZARDCAN', rotation = vector3(0,92.5,0)},
				[`WEAPON_FERTILIZERCAN`] = {object = `w_am_jerrycan_sf`, item = 'WEAPON_FERTILIZERCAN', rotation = vector3(0,92.5,0)},
				[`WEAPON_MACHETE`] = {object = `w_me_machette_lr`, item = 'WEAPON_MACHETE', rotation = vector3(0,92.5,0)},
				[`WEAPON_NIGHTSTICK`] = {object = `w_me_nightstick`, item = 'WEAPON_NIGHTSTICK', rotation = vector3(0,92.5,0)},
				[`WEAPON_PETROLCAN`] = {object = `w_am_jerrycan`, item = 'WEAPON_PETROLCAN', rotation = vector3(0,92.5,0)},
				[`WEAPON_POOLCUE`] = {object = `w_me_poolcue`, item = 'WEAPON_POOLCUE', rotation = vector3(0,92.5,0)},
				[`WEAPON_STONE_HATCHET`] = {object = `w_me_stonehatchet`, item = 'WEAPON_STONE_HATCHET', rotation = vector3(0,92.5,0)},
				[`WEAPON_WRENCH`] = {object = `w_me_wrench`, item = 'WEAPON_WRENCH', rotation = vector3(0,92.5,0)},
				[`WEAPON_CANDYCANE`] = {object = `w_me_candy_xm3`, item = 'WEAPON_CANDYCANE', rotation = vector3(0,92.5,0)},
		},
}